### PR TITLE
Passing a directory path implicitly watches directory contents, undoes accidental breaking change and fixes #229

### LINKED ISSUE #229: Absolute paths in glob not working
There is an issue when using absolute paths as globs in `gulp-watch`.
Example:
```
var gulp = require('gulp'),
    watch = require('gulp-watch'),
	glob = '/home/username/tmp/client/js/**/*.js';

const opts = { };

gulp.task('stream', function () {
    return gulp.src(glob, opts)
        .pipe(watch(glob, opts))
        .pipe(gulp.dest('build'));
});
```
Gulpfile is located under: `/home/username/tmp/gulpfile.js`.
This was working without problems in `4.3.5`, and was broken by [this commit](https://github.com/floatdrop/gulp-watch/commit/678a8f19fdaf1416b49f40da980b7471dea5e4c6). After the change matching of absolute glob and relative file path is not correct and `glob` is always `-1`.
Please provide more information about why this check is needed in that situation.

Thanks for the great work on the plugin.

### PR DESCRIPTION
**Pull request by UltCombo**
Also refactor event filtering and add logging for unexpected watched files.

### CODE REVIEW

File: test/test-cwd.js [hunk 1]
```diff
@@ -21,7 +21,14 @@ describe('cwd', function () {
 
 	it('should respect opts.cwd', function (done) {
 		w = watch('index.js', {cwd: fixtures('')}, function (file) {
-			file.relative.should.eql(path.normalize('test/fixtures/index.js'));
+			file.relative.should.eql(path.normalize('index.js'));
```
Comment (UltCombo) [inline test/test-cwd.js]: TODO: https://github.com/floatdrop/gulp-watch/issues/229#issuecomment-226092111

File: test/test-dir.js [hunk 2]
```diff
@@ -20,14 +20,14 @@ describe('dir', function () {
 		w.close();
 	});
 
-	it('should not watch files inside directory', function (done) {
+	it('should watch files inside directory', function (done) {
```
Comment (UltCombo) [inline test/test-dir.js]: NOTE: this is the correct behavior; it aligns with gulp-watch <= 4.3.5 as well as gulp 4's `gulp.watch`.

File: test/test-cwd.js (hunk 1 above)
Comment (UltCombo) [inline test/test-cwd.js]: Done. https://github.com/floatdrop/gulp-watch/issues/229#issuecomment-226969325
